name: flutter_images_saver
description: Flutter-приложение, которое умеет скачивать картинки из интернета и хранить их на локальном диске.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14
  http: ^0.13.6
  uuid: ^3.0.7
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
