name: flutter_sensitive_data_storage
description: Flutter-приложение, которое хранит данные о пользователях.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^2.7.0
  path_provider: ^2.0.14
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  path: ^1.8.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  drift_dev: ^2.7.0
  freezed: ^2.3.3

flutter:
  uses-material-design: true